[2024-08-08 21:18:19] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:20] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/1/ HTTP/1.1" 200 None
[2024-08-08 21:18:20] [tests.test_endpoints_get] [INFO] - Checking if status code is 200
[2024-08-08 21:18:20] [tests.test_endpoints_get] [INFO] - Checking if response body has content
[2024-08-08 21:18:20] [root] [INFO] - tests/test_endpoints_get.py::test_get_endpoint_resource -- PASSED --
[2024-08-08 21:18:20] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:22] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /wrong_endpoint HTTP/1.1" 404 None
[2024-08-08 21:18:22] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:22] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:22] [root] [INFO] - tests/test_endpoints_get.py::test_get_nonexistent_endpoint -- PASSED --
[2024-08-08 21:18:22] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:23] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/99999999999999 HTTP/1.1" 404 None
[2024-08-08 21:18:23] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:23] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:23] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[99999999999999] -- PASSED --
[2024-08-08 21:18:23] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:23] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/-1 HTTP/1.1" 404 None
[2024-08-08 21:18:23] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:23] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:23] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[-1] -- PASSED --
[2024-08-08 21:18:23] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:25] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/0.5 HTTP/1.1" 404 None
[2024-08-08 21:18:25] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:25] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:25] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[0.5] -- PASSED --
[2024-08-08 21:18:25] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:26] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/! HTTP/1.1" 404 None
[2024-08-08 21:18:26] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:26] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:26] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[!] -- PASSED --
[2024-08-08 21:18:26] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:27] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/test HTTP/1.1" 404 None
[2024-08-08 21:18:27] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-08 21:18:27] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-08 21:18:27] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[test] -- PASSED --
[2024-08-08 21:18:27] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:28] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-08 21:18:28] [root] [INFO] - tests/test_endpoints_post.py::test_post_new_resource -- PASSED --
[2024-08-08 21:18:28] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:30] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-08 21:18:30] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-08 21:18:31] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/ff8081819132b5db0191336da13701f5 HTTP/1.1" 200 None
[2024-08-08 21:18:31] [root] [INFO] - tests/test_endpoints_post.py::test_created_resource_exists -- PASSED --
