[2024-08-07 23:13:45] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:46] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/1/ HTTP/1.1" 200 None
[2024-08-07 23:13:46] [tests.test_endpoints_get] [INFO] - Checking if status code is 200
[2024-08-07 23:13:46] [tests.test_endpoints_get] [INFO] - Checking if response body has content
[2024-08-07 23:13:46] [root] [INFO] - tests/test_endpoints_get.py::test_get_endpoint_resource -- PASSED --
[2024-08-07 23:13:46] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:47] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /wrong_endpoint HTTP/1.1" 404 None
[2024-08-07 23:13:47] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:47] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:47] [root] [INFO] - tests/test_endpoints_get.py::test_get_nonexistent_endpoint -- PASSED --
[2024-08-07 23:13:47] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:47] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/99999999999999 HTTP/1.1" 404 None
[2024-08-07 23:13:47] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:47] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:47] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[99999999999999] -- PASSED --
[2024-08-07 23:13:47] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:48] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/-1 HTTP/1.1" 404 None
[2024-08-07 23:13:48] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:48] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:48] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[-1] -- PASSED --
[2024-08-07 23:13:48] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:48] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/0.5 HTTP/1.1" 404 None
[2024-08-07 23:13:48] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:48] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:48] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[0.5] -- PASSED --
[2024-08-07 23:13:48] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:49] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/! HTTP/1.1" 404 None
[2024-08-07 23:13:49] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:49] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:49] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[!] -- PASSED --
[2024-08-07 23:13:49] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-07 23:13:50] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/test HTTP/1.1" 404 None
[2024-08-07 23:13:50] [tests.test_endpoints_get] [INFO] - Checking if status code is 404
[2024-08-07 23:13:50] [tests.test_endpoints_get] [INFO] - Checking if error message is present in response body
[2024-08-07 23:13:50] [root] [INFO] - tests/test_endpoints_get.py::test_get_invalid_resource[test] -- PASSED --
[2024-08-07 23:13:50] [root] [INFO] - tests/test_endpoints_post.py::test_post_new_resource -- PASSED --
